name: Continuous Integration

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
  schedule:
    - cron: '30 2 * * 1,4' # Every Monday and Thursday @ 2h30am UTC

jobs:
  test:
    uses: ratt-ru/rarg-gh-workflows/.github/workflows/python-test.yml@main
    with:
      os-matrix: ["ubuntu-24.04", "macos-15"]
